server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: jefjafledmfsjretpowjlkvmklsahfkjashcmasadajfksdfalsdfjskdfkjsdjkfsdjakfjsdkfjasdlkfjskdaljfkdsajflkasjdkfajskldfjksaldjfkldsajfkasjdklfjsakdfjlsjkfljsdklafjsdklfjskladjfklasdjfikleijioueifiuriwoeutqiwcnfhjskhfjaskfsdhfjkashfuwiyrtwiurywiryutg
